
DH:
  J1:
    alpha: 0
    a: 0
    d: 0.2592
    theta: 0
  J2:
    alpha: 1.5707963
    a: 0
    d: 0
    theta: 3.14158 # 1.5707963
  J3:
    alpha: 0
    a: 0.450
    d: 0
    theta: -1.5707963
  WA:
    alpha: 1.5707963
    a: 0.12 # 0.117
    d: 0.330
    theta: -1.5707963

