
DH:
  J4:
    alpha: -1.5707963
    a: 0
    d: 0.088
    theta: 1.5707963
  J5:
    alpha: -1.5707963
    a: 0
    d: 0
    theta: 1.5707963
  J6:
    alpha: -1.5707963
    a: 0
    d: 0.0695
    theta: 0
